package main

import (
	"bytes"
	"cmp"
	"errors"
	"io"
	"os"
	"path"
	"strings"
	"testing"
	"testing/iotest"
)

const uncondensed = `package main

import "fmt"

func greet(first, last string) string {
	return fmt.Sprintf(
		"Hello, %s %s!",
		first,
		last,
	)
}
`

const condensed = `package main

import "fmt"

func greet(first, last string) string {
	return fmt.Sprintf("Hello, %s %s!", first, last)
}
`

const (
	generatedPrefix    = "// Code generated by test; DO NOT EDIT.\n\n"
	generated          = generatedPrefix + uncondensed
	generatedCondensed = generatedPrefix + condensed
)

var errTest = errors.New("test error")

type errWriter struct{}

func (errWriter) Write([]byte) (int, error) { return 0, errTest }

func TestRun(t *testing.T) {
	tests := []struct {
		name       string
		args       []string
		stdin      io.Reader
		stdout     io.Writer
		files      map[string]string
		wantCode   int
		wantStdout string
		wantFiles  map[string]string
		wantStderr string
	}{
		// Flags
		{
			name:       "help",
			args:       []string{"-help"},
			wantStderr: "Usage: gocondense [options]",
		},
		{
			name:       "max_len_prevents_condensing",
			args:       []string{"-max-len=10"},
			stdin:      strings.NewReader(uncondensed),
			wantStdout: uncondensed,
		},
		{
			name:       "small_tab_width_allows_condensing",
			args:       []string{"-tab-width=2", "-max-len=50"}, // 2+48=50, fits
			stdin:      strings.NewReader(uncondensed),
			wantStdout: condensed,
		},
		{
			name:       "large_tab_width_prevents_condensing",
			args:       []string{"-tab-width=8", "-max-len=50"}, // 8+48=56, too long
			stdin:      strings.NewReader(uncondensed),
			wantStdout: uncondensed,
		},
		{
			name:       "unknown_flag",
			args:       []string{"-unknown"},
			wantCode:   2,
			wantStderr: "flag provided but not defined: -unknown",
		},
		{
			name:       "negative_max_len",
			args:       []string{"-max-len=-1"},
			wantCode:   2,
			wantStderr: "max-len and tab-width must not be negative",
		},
		{
			name:       "negative_tab_width",
			args:       []string{"-tab-width=-1"},
			wantCode:   2,
			wantStderr: "max-len and tab-width must not be negative",
		},
		// Stdin
		{
			name:       "formats_stdin",
			stdin:      strings.NewReader(uncondensed),
			wantStdout: condensed,
		},
		{
			name:       "invalid_go_stdin",
			stdin:      strings.NewReader("not valid go"),
			wantCode:   2,
			wantStderr: "Error formatting code:",
		},
		{
			name:       "stdin_read_error",
			stdin:      iotest.ErrReader(errTest),
			wantCode:   2,
			wantStderr: "Error reading from stdin:",
		},
		{
			name:       "stdout_write_error",
			stdin:      strings.NewReader(uncondensed),
			stdout:     errWriter{},
			wantCode:   2,
			wantStderr: "Error writing to stdout:",
		},
		// Files
		{
			name: "files",
			args: []string{"a.go", "b.go"},
			files: map[string]string{
				"a.go": uncondensed,
				"b.go": uncondensed,
			},
			wantFiles: map[string]string{
				"a.go": condensed,
				"b.go": condensed,
			},
		},
		{
			name:       "invalid_go_file",
			args:       []string{"bad.go"},
			files:      map[string]string{"bad.go": "not valid go"},
			wantCode:   2,
			wantStderr: "Error formatting file",
		},
		{
			name:       "non_existent_path",
			args:       []string{"nonexistent.go"},
			wantCode:   2,
			wantStderr: "Error stating path nonexistent.go:",
		},
		// Directories
		{
			name: "directory_non_recursive",
			args: []string{"."},
			files: map[string]string{
				"top.go":     uncondensed,
				"sub/sub.go": uncondensed,
			},
			wantFiles: map[string]string{
				"top.go":     condensed,
				"sub/sub.go": uncondensed,
			},
		},
		{
			name: "directory_recursive",
			args: []string{"./..."},
			files: map[string]string{
				"sub/sub.go": uncondensed,
			},
			wantFiles: map[string]string{
				"sub/sub.go": condensed,
			},
		},
		// Skipping
		{
			name: "skip",
			args: []string{"./..."},
			files: map[string]string{
				".hidden.go":    uncondensed,
				"generated.go":  generated,
				"not_go.txt":    uncondensed,
				"testdata/t.go": uncondensed,
				"vendor/v.go":   uncondensed,
			},
			wantFiles: map[string]string{
				".hidden.go":    uncondensed,
				"generated.go":  generated,
				"not_go.txt":    uncondensed,
				"testdata/t.go": uncondensed,
				"vendor/v.go":   uncondensed,
			},
		},
		{
			name: "bypass_skip",
			args: []string{"generated.go", "not_go.txt", "vendor", "testdata", "tools"},
			files: map[string]string{
				"go.mod":        "module test\n\ngo 1.25\n\nignore tools\n",
				"generated.go":  generated,
				"not_go.txt":    uncondensed,
				"testdata/t.go": uncondensed,
				"tools/tool.go": uncondensed,
				"vendor/v.go":   uncondensed,
			},
			wantFiles: map[string]string{
				"generated.go":  generatedCondensed,
				"not_go.txt":    condensed,
				"testdata/t.go": condensed,
				"tools/tool.go": condensed,
				"vendor/v.go":   condensed,
			},
		},
		{
			name: "gomod_ignore",
			args: []string{"./..."},
			files: map[string]string{
				"go.mod":             "module test\n\ngo 1.25\n\nignore gen\n\nignore ./tools\n",
				"sub/gen/gen.go":     uncondensed,
				"sub/tools/tools.go": uncondensed,
				"tools/tools.go":     uncondensed,
			},
			wantFiles: map[string]string{
				"sub/gen/gen.go":     uncondensed, // ignore gen: matches at any depth
				"sub/tools/tools.go": condensed,   // ignore ./tools: no match at depth
				"tools/tools.go":     uncondensed, // ignore ./tools: matches at root
			},
		},
		{
			name: "gomod_ignore_nested_module",
			args: []string{"./..."},
			files: map[string]string{
				"go.mod":         "module test\n\ngo 1.25\n\nignore gen\n",
				"sub/go.mod":     "module test/sub\n\ngo 1.25\n",
				"sub/gen/gen.go": uncondensed,
			},
			wantFiles: map[string]string{
				"sub/gen/gen.go": condensed,
			},
		},
		{
			name: "malformed_gomod",
			args: []string{"./..."},
			files: map[string]string{
				"go.mod":     "invalid{",
				"sub/sub.go": uncondensed,
			},
			wantFiles: map[string]string{
				"sub/sub.go": condensed,
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Chdir(t.TempDir())
			clear(modIgnoreCache)

			for name, content := range tt.files {
				if err := os.MkdirAll(path.Dir(name), 0o755); err != nil {
					t.Fatal(err)
				}
				if err := os.WriteFile(name, []byte(content), 0o644); err != nil {
					t.Fatal(err)
				}
			}

			var stdout, stderr bytes.Buffer
			code := run(append([]string{"gocondense"}, tt.args...), tt.stdin, cmp.Or(tt.stdout, io.Writer(&stdout)), &stderr)

			if code != tt.wantCode {
				t.Fatalf("exit code = %d, want %d: %s", code, tt.wantCode, stderr.String())
			}
			if stdout.String() != tt.wantStdout {
				t.Errorf("stdout:\ngot:  %q\nwant: %q", stdout.String(), tt.wantStdout)
			}
			if tt.wantStderr == "" && stderr.String() != "" {
				t.Errorf("unexpected stderr: %s", stderr.String())
			} else if tt.wantStderr != "" && !strings.HasPrefix(stderr.String(), tt.wantStderr) {
				t.Errorf("stderr:\ngot:  %q\nwant: %q", stderr.String(), tt.wantStderr)
			}
			for name, want := range tt.wantFiles {
				got, err := os.ReadFile(name)
				if err != nil {
					t.Fatalf("reading %s: %v", name, err)
				}
				if string(got) != want {
					t.Errorf("%s:\ngot:  %q\nwant: %q", name, string(got), want)
				}
			}
		})
	}
}
