package gocondense_test

import (
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"

	"github.com/abemedia/gocondense"
)

var update = flag.Bool("update", false, "update .golden files")

func TestFormat(t *testing.T) {
	matches, err := filepath.Glob("testdata/*.input")
	if err != nil {
		t.Fatal(err)
	}

	for _, inputFile := range matches {
		base := strings.TrimSuffix(inputFile, ".input")
		goldenFile := base + ".golden"

		name := filepath.Base(base)
		t.Run(name, func(t *testing.T) {
			input, err := os.ReadFile(inputFile)
			if err != nil {
				t.Fatalf("failed to read input file %s: %v", inputFile, err)
			}

			got, err := gocondense.Format(input)
			if err != nil {
				t.Fatalf("failed to format %s: %v", inputFile, err)
			}

			if *update { // Update golden file
				if err := os.WriteFile(goldenFile, got, 0o600); err != nil {
					t.Fatalf("failed to update golden file %s: %v", goldenFile, err)
				}
				return
			}

			want, err := os.ReadFile(goldenFile)
			if err != nil {
				t.Fatalf("failed to read golden file %s: %v", goldenFile, err)
			}

			if diff := cmp.Diff(want, got); diff != "" {
				t.Error(diff)
			}
		})
	}
}

func TestFormatter(t *testing.T) {
	uncondensed := `package main

import "fmt"

func greet(first, last string) string {
	return fmt.Sprintf(
		"Hello, %s %s!",
		first,
		last,
	)
}
`
	condensed := `package main

import "fmt"

func greet(first, last string) string {
	return fmt.Sprintf("Hello, %s %s!", first, last)
}
`
	generatedPrefix := "// Code generated by test; DO NOT EDIT.\n\n"
	generated := generatedPrefix + uncondensed
	generatedCondensed := generatedPrefix + condensed

	tests := []struct {
		name      string
		config    *gocondense.Config
		input     string
		want      string
		wantPanic string
		wantErr   bool
	}{
		{
			name:   "nil_config",
			config: nil,
			input:  uncondensed,
			want:   condensed,
		},
		{
			name:   "zero_config",
			config: &gocondense.Config{},
			input:  uncondensed,
			want:   condensed,
		},
		{
			name: "max_len_prevents_condensing",
			config: &gocondense.Config{
				MaxLen: 50,
			},
			input: uncondensed,
			want:  uncondensed,
		},
		{
			name: "tab_width_prevents_condensing",
			config: &gocondense.Config{
				TabWidth: 40,
			},
			input: uncondensed,
			want:  uncondensed,
		},
		{
			name: "tab_width_allows_condensing",
			config: &gocondense.Config{
				MaxLen:   50,
				TabWidth: 2,
			},
			input: uncondensed,
			want:  condensed,
		},
		{
			name: "skip_generated",
			config: &gocondense.Config{
				SkipGenerated: true,
			},
			input: generated,
			want:  generated,
		},
		{
			name: "format_generated",
			config: &gocondense.Config{
				SkipGenerated: false,
			},
			input: generated,
			want:  generatedCondensed,
		},
		{
			name: "negative_max_len",
			config: &gocondense.Config{
				MaxLen: -1,
			},
			wantPanic: "gocondense: MaxLen and TabWidth must not be negative",
		},
		{
			name: "negative_tab_width",
			config: &gocondense.Config{
				TabWidth: -1,
			},
			wantPanic: "gocondense: MaxLen and TabWidth must not be negative",
		},
		{
			name:    "invalid_syntax",
			input:   "package main\n\nfunc main() {\n\treturn\n", // missing closing brace
			wantErr: true,
		},
		{
			name:    "empty_input",
			input:   "",
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if tt.wantPanic != "" {
				defer func() {
					if r := recover(); r != tt.wantPanic {
						t.Fatalf("panic = %q, want %q", r, tt.wantPanic)
					}
				}()
			}
			formatter := gocondense.New(tt.config)
			got, err := formatter.Format([]byte(tt.input))
			if (err != nil) != tt.wantErr {
				t.Fatalf("err = %v, wantErr = %v", err, tt.wantErr)
			}
			if diff := cmp.Diff(tt.want, string(got)); diff != "" {
				t.Error(diff)
			}
		})
	}
}
